# Cargo configuration for faster builds

[build]
# Use all available CPU cores for parallel compilation
jobs = 0

[target.x86_64-unknown-linux-gnu]
# Use faster linker on Linux
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
# Use faster linker on Windows
rustflags = ["-C", "link-arg=/DEBUG:NONE"]

[target.x86_64-apple-darwin]
# Use faster linker on macOS
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
# Enable faster incremental compilation
CARGO_INCREMENTAL = "1" 